controller_manager:
  ros__parameters:
    update_rate: 50
    scout_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    scout_base_controller:
      type: diff_drive_controller/DiffDriveController

scout_base_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel', 'rear_left_wheel']
    right_wheel_names: ['front_right_wheel', 'rear_right_wheel']
    wheel_separation: 0.49
    wheel_radius: 0.0875
    cmd_vel_timeout: 0.25
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    use_stamped_vel: true
    position_feedback: true